### ISSUE TITLE
A clean database

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#138]
This is a meta issue to make sure we capture everything that's spread around in different issues now.

- [x] Check all [entries made by the sci-fi team](https://github.com/MachineVisionUiB/machinevision/issues/128) and close the issue.
- [x] Go through the [Needs discussion list](https://machine-vision.no/record-status/needs-discussion)
- [x] Go through and make sure there are no [drafts](https://machine-vision.no/record-status/draft). 08.11.2021: _Brave New World_ is only draft left. <strike>Note that some are Linn Heidi's, so we have to figure out what to do with these. Also, some Persons show up as drafts even if they have no option to chance status. See further discussion at https://github.com/MachineVisionUiB/machinevision/issues/141</strike>
- [x] Go through and make sure there are no [stubs](https://machine-vision.no/record-status/stub)
- [x] Locate if there are any "missing data" fields. Jill mentioned it was three, but I can't find them.
- [x] Ask Anne to fix [her entry](https://machine-vision.no/user/anne) by adding a situation.
- [x] Go through [entries entered by Admin](https://machine-vision.no/user/admin) or by using [admin content](https://machine-vision.no/admin/content?title=&type=All&status=All&langcode=All&uid=admin+%281%29)
- [x] [Fix verbs](https://github.com/MachineVisionUiB/machinevision/issues/131) and close the issue. <strike>Also check e.g. "surveilling" (currently three entries).</strike>
- [x] Check the [Fix characters list](https://github.com/MachineVisionUiB/machinevision/issues/122) and close the issue.
- [x] Check the science fiction tag and character actions in [this issue](https://github.com/MachineVisionUiB/machinevision/issues/112) and close the issue.
- [x] Check [whether we need to add back uses of Environment as Entity](https://github.com/MachineVisionUiB/machinevision/issues/134) and close the issue.
- [x] Help Ragnhild figure out these anime characters' race/ethnicity: [Asuka](https://machine-vision.no/character/asuka-langley-soryu), [Aiba](https://machine-vision.no/character/aiba), [Date](https://machine-vision.no/character/kaname-date), [Kazuto](https://machine-vision.no/character/kazuto-kirigaya), [Asuna](https://machine-vision.no/character/asuna-yuuki), [Rio](https://machine-vision.no/character/rio), [Shinji](https://machine-vision.no/character/shinji-ikari), [Rey](https://machine-vision.no/character/rey-ayanami), [Cortana](https://machine-vision.no/character/cortana). Might also apply for other anime characters. Already decided in chat on 2B and Cloud Strife as "white".
- [x] Go through [Linn Heidi's characters](https://machine-vision.no/admin/content?title=&type=character&status=All&langcode=All&uid=Linn+Heidi+%285%29) and make sure they have all five "traits" registered with a tag, and that the character has a backlink to the work (some are missing in the work). Linda does the artworks, Ragnhild does the rest. 
- [x] Remove the parenthesis on the [Horror (revisit) tag](https://discord.com/channels/532147442666438675/611854873691947008/829284337605935134).
- [x] Write descriptions for Art, Games, Narrative overview pages (e.g. https://machine-vision.no/creative-work-publication-type/art)
- [x] Remove Other category, first moving all Music videos to Narrative, <strike>all ads to Narrative and the Board game to Game</strike>.

**Comment by notsaved** [comment]
checked the ethnicity of anime characters - let me know if there's more doubtful ones!

**Comment by notsaved** [comment]
also gone through the "Needs discussion list" and solved all entries I could. The remaining ones (a page or so) are marked as to be discussed or not clear what the problem is - I recommend to maybe go through them as a group

**Comment by steinmb** [comment]
Blew through all `entries entered by Admin` and set them all to user Jill.

**Comment by jilltxt** [comment]
@steinmb BRILLIANT! I had wondered if that was possible - that's really helpful :)
