### ISSUE TITLE
Meta issues

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#31]
To do list:

- [ ] To go through all "coding schema" issues on GitHub

- [ ] Define missing definitions in Wiki

- [ ] Revisit definitions that needs to be revisited

**Comment by jilltxt** [comment]
Closing this as I think we've either done most of it or it's less relevant now.
