### ISSUE TITLE
Upgrade from Drupal 7 to Drupal 9

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#61]
>Drupal 7 was first released in January 2011. In November 2021, after over a decade, Drupal 7 will reach end of life (EOL). (More information on why this date was chosen.) Official community support for version 7 will end, along with support provided by the Drupal Association on Drupal.org. This means that automated testing services for Drupal 7 will be shut down, and there will be no more updates provided by the Drupal Security Team. https://www.drupal.org/psa-2019-02-25

## Pre-flight

Drupal 9 is released June 3. https://www.drupal.org/about/9 . Tasks to make sure it works.

* [x] Drupal 9 readiness #89

## Migration overview

Data types to migrate.

### Nodes

* [x] #81 - Character - migrate all fields
* [x] #84 - Machine Vision Situations - migrate all fields except "Old Stuff"
* [x] #79 - Creative Works - migrate all fields except ELMCIP Legacy
* [x] #82 - Person - migrate all fields

### Location

* [x] Person Location - country

### Taxonomy

* [x] Sexuality
* [x] Creative Work Publication Type
* [x] Record status
* [x] Central Topics
* [x] Technologies
* [x] Sentiment
* [x] Race/ethnicity
* [x] Colours
* [x] Gender
* [x] Generic Entities
* [x] Individual or Group
* [x] Verbs
* [x] Visual characteristics
* [x] Species
* [x] Age

### Paragraphs

* [x] Character Actions (character_actions)
* [x] Generic Entity Action (Thing) (generic_entity_action)
* [x] Technology Actions (technology_actions)

### Comments
* [x] node comments

### Files
* [x] #86 - Files, images, documents and videos to core Media.

### Users
* [x] User groups
* [x] User account.

**Comment by jilltxt** [comment]
Figure out what needs to be done, considering database will be “live” until spring 2023 and then archived and a static html-version (and downloadable content)  all that is left.

**Comment by jilltxt** [comment]
Creative Works - migrate all fields **except** ELMCIP Legacy
Character - migrate all fields
Machine Vision Situations - migrate all fields **except** "Old Stuff"
Person - migrate all fields

Only the taxonomies in **bold** should be migrated to Drupal 8.

**Creative Work Publication Type**
Critical Writing Publication Type 
Language 
**Record status** 
Event type 
**Central Topics** 
**Technologies**
**Sentiment**
Focaliser (was: agent/user) 
**Race/ethnicity**
Aware
**Colours**
Functioning
**Gender**
**Generic Entities**
Happening
**Individual or Group**
Operation of machine vision
Owner-type
Publisher and Journal types
**Sexuality**
**Verbs**
**Visual characteristics**
**Species**
**Age**

**Comment by steinmb** [comment]
Ikke så lett for andre å følge arbeidet her. Har oppdatert issue summary slik at det gir en bedre oversikt. Burde hjelpe bittelitt på.

Detter er oversikt fra min dev. for de som er spesiellt interesert.

```

 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------
  Group                         Migration ID                                       Status   Total   Imported   Unprocessed   Last Imported
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------
  UiB content (uib_nodes)       uib_node_character                                 Idle     101     0          101
  UiB content (uib_nodes)       uib_node_machine_vision_situation                  Idle     158     0          158
  UiB content (uib_nodes)       uib_node_person                                    Idle     168     0          168
  UiB content (uib_nodes)       uib_node_work                                      Idle     160     0          160

  UiB Users (uib_users)         uib_user_role                                      Idle     10      0          10
  UiB Users (uib_users)         uib_user                                           Idle     10      0          10

  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_age                              Idle     4       0          4
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_creative_work_publication_type   Idle     21      0          21
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_gender                           Idle     4       0          4
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_race                             Idle     8       0          8
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_record_status                    Idle     4       0          4
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_species                          Idle     5       0          5
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_technologies                     Idle     24      0          24
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_themes                           Idle     40      0          40
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------
```

**Comment by steinmb** [comment]
All taxonomy terms vocab. have been added to the migration module. Test run in dev:

```
drush ms --group=uib_taxonomy

 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------
  Group                         Migration ID                                       Status   Total   Imported   Unprocessed   Last Imported
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_age                              Idle     4       0          4
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_colours                          Idle     24      0          24
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_creative_work_publication_type   Idle     21      0          21
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_gender                           Idle     5       0          5
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_generic_entities                 Idle     49      0          49
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_individual_or_group              Idle     2       0          2
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_race                             Idle     9       0          9
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_record_status                    Idle     5       0          5
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_sentiment                        Idle     21      0          21
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_species                          Idle     5       0          5
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_technologies                     Idle     26      0          26
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_themes                           Idle     40      0          40
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_verbs                            Idle     547     0          547
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_visual_characteristics           Idle     242     0          242
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------
```

Looks OK, test migrate:

```
drush migrate:import --group=uib_taxonomy
 [notice] Processed 4 items (4 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_age'
 [notice] Processed 24 items (24 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_colours'
 [notice] Processed 21 items (21 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_creative_work_publication_type'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_gender'
 [notice] Processed 49 items (49 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_generic_entities'
 [notice] Processed 2 items (2 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_individual_or_group'
 [notice] Processed 9 items (9 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_race'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_record_status'
 [notice] Processed 21 items (21 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_sentiment'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_species'
 [notice] Processed 26 items (26 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_technologies'
 [notice] Processed 40 items (40 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_themes'
 [notice] Processed 547 items (547 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_verbs'
 [notice] Processed 242 items (242 created, 0 updated, 0 failed, 0 ignored) - done with 'uib_taxonomy_term_visual_characteristics'
```

Nothing blew up though I need to do a quick verify that all vocab. god populated. New status:

```
drush ms --group=uib_taxonomy
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------------
  Group                         Migration ID                                       Status   Total   Imported   Unprocessed   Last Imported
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------------
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_age                              Idle     4       4          0             2020-02-10 08:40:52
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_colours                          Idle     24      24         0             2020-02-10 08:40:53
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_creative_work_publication_type   Idle     21      21         0             2020-02-10 08:40:54
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_gender                           Idle     5       5          0             2020-02-10 08:40:54
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_generic_entities                 Idle     49      49         0             2020-02-10 08:40:54
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_individual_or_group              Idle     2       2          0             2020-02-10 08:40:55
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_race                             Idle     9       9          0             2020-02-10 08:40:55
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_record_status                    Idle     5       5          0             2020-02-10 08:40:55
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_sentiment                        Idle     21      21         0             2020-02-10 08:40:55
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_species                          Idle     5       5          0             2020-02-10 08:40:55
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_technologies                     Idle     26      26         0             2020-02-10 08:40:56
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_themes                           Idle     40      40         0             2020-02-10 08:40:56
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_verbs                            Idle     547     547        0             2020-02-10 08:41:02
  UiB taxonomy (uib_taxonomy)   uib_taxonomy_term_visual_characteristics           Idle     242     242        0             2020-02-10 08:41:05
 ----------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------------
```

**Comment by steinmb** [comment]
Teste migrated all nodes. Looks OK, moving on to file to file migration where we move from:
https://www.drupal.org/project/media
to
Drupal 8 core module: https://www.drupal.org/node/2863992

**Comment by steinmb** [comment]
Nothing left in here. Closing this. Going to create new one for stuff I discover while testing.
