### ISSUE TITLE
Migrate files, images, documents, videos from D7 media to Drupal 8/9 core media

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#86]
In Drupal 7 media is provided by https://www.drupal.org/project/media module. Core in Drupal 8 now support this out of the box and we should make sure we migrate directly here during the upgrade

* Core: https://www.drupal.org/project/drupal/issues/2835825
* https://www.drupal.org/project/media_migration
* https://www.drupal.org/project/migrate_file_to_media

## Drupal 9
* Target media type in Drupal 9: Remote video - `remote_video`.
* Field: Video URL `field_media_oembed_video`

## Data structures

Data in Drupal 7 is stored in different ways. Something locally, something remote. All store different type of meta data. The meta data is normally stored as fields on the file entity or as properties. Sometime both.

### Locally stored audio
None

### Locally stored documents
None.

### Locally stored video
None

### Locally stored images
* Alt property: field_file_image_alt_text
* Title property: field_file_image_title_text
* Created time stamp
* Entity title/name

### Remote stored video

* Flickr: None
* Vimeo:
    * Filename: Used as title
    * URI: link to original video
    * Timestamp: Created in Drupal date
* Youtube:
    * Filename: Used as title
    * URI: link to original video
    * Timestamp: Created in Drupal date

### Character

```

    Multimedia
        Field type: Image
        Widget: Media browser
        Field: field_media
        Media types: Image

    Image (Screenshot)
        Field type: Image
        Widget: Media browser
        Field: field_image
        Media types: Image

```

## Tasks

* [x] Migrate locally storedd Images
* [x] Remote videos Youtube
* [x] Remote videos Vimeo

**Comment by steinmb** [comment]
Re-check that all properties was correctly migrated and by task II converted to Media entity in D9.

```
 ----------------------- -------------- -------- ------- ---------- ------------- ---------------------
  Group                   Migration ID   Status   Total   Imported   Unprocessed   Last Imported
 ----------------------- -------------- -------- ------- ---------- ------------- ---------------------
  UiB files (uib_files)   uib_file       Idle     475     475        0             2020-05-12 09:20:10
  UiB files (uib_files)   uib_image      Idle     475     475        0             2020-05-12 09:20:36
 ----------------------- -------------- -------- ------- ---------- ------------- ---------------------
```

**Comment by steinmb** [comment]
That seemed to be right:

![Screen Shot 2020-05-12 at 10 31 45](https://user-images.githubusercontent.com/683617/81661281-2ea90980-943c-11ea-809f-7b77fda241fd.png)
![Screen Shot 2020-05-12 at 10 31 16](https://user-images.githubusercontent.com/683617/81661290-3072cd00-943c-11ea-8683-fce18bd5a1a0.png)
![Screen Shot 2020-05-12 at 10 30 58](https://user-images.githubusercontent.com/683617/81661292-310b6380-943c-11ea-81de-397b9608950e.png)

**Comment by steinmb** [comment]
For Youtube we need to during the data migration transform the stored URL from `youtube://v/` to `https://youtu.be/`. Media Youtube in Drupal 7 register a separate PHP stream wrapper pr. video provider. We might have to do something similar for Vimeo.

**Comment by steinmb** [comment]
My local db. Drupal 7 snapshot is a little old though I flushed out a few Youtube video resources that no longer exists:

https://www.youtube.com/oembed?url=https://youtu.be/57H1LPlYhG4
https://www.youtube.com/oembed?url=https://youtu.be/Y7dKFr-O1pU
https://www.youtube.com/oembed?url=https://youtu.be/-a2vKyFsNqo
https://www.youtube.com/oembed?url=https://youtu.be/DvV1eYRKRNY/l/RDDvV1eYRKRNY
https://www.youtube.com/oembed?url=https://youtu.be/9cmyIYNDlmw/l/RD9cmyIYNDlmw
https://www.youtube.com/oembed?url=https://youtu.be/wm3zPLHt8OE

Working resource reference:
https://www.youtube.com/oembed?url=https://youtu.be/KTT7i3SKpMQ

**Comment by steinmb** [comment]
Vimeo seem similar to Youtube. Needs to rewrite the URI stored in Drupal 7.

      search: 'vimeo://v/'
      replace: 'https://vimeo.com/'

**Comment by steinmb** [comment]
Flushed out one Vimeo that no longer exist:
https://vimeo.com/api/oembed.json?url=https://vimeo.com/338726032

**Comment by steinmb** [comment]
Mental note: No avoid having to use debugger do we now have local changes to

    OEmbed::getMetadata();

Logging URL to watchdog when trying to fetch metadata.

**Comment by steinmb** [comment]
Created follow up task for content creators in #87 - I think we are done here, I think. Yay!
