### ISSUE TITLE
Fixes needed in editing mode after upgrade

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#95]
- [x] Issue #96 - Search box/page.
- [ ] issue #103 - Year should accept just the year - currently requires a precise date in YYYY-MM-DD format.
- [x] Several fields that should have check boxes or pull down menus have free typing - hard to remember all the techs or sentiments, so this should be changed. Goes for: publication type, Topics, Technologies Used, Technologies References, Sentiment, Record status. Alternatively we could list all the possible words in the help text if people prefer that. 
- [ ] Issue #102 - Add inline editing of Situations in the Creative Works entry. Now you can only add existing Situations, it would be nice to be able to add new Situations directly from the Creative Works entry.

**Comment by steinmb** [comment]
Split out the search bit into #96 Since it req. work/testing etc. I'll have a look.

**Comment by ragsol** [comment]
Also, not sure if it goes here, but from the Knowledgebase's introduction (https://machine-vision.no/knowledgebase) the publication types don't work (e.g. "game", https://machine-vision.no/creative-work-publication-type/game). Funky enough, "topics" work. Further down, "game" works, but leads here: https://machine-vision.no/taxonomy/term/3 - so I guess it's just about the links in the introductory text.

**Comment by steinmb** [comment]
>Also, not sure if it goes here, but from the Knowledgebase's introduction (https://machine-vision.no/knowledgebase) the publication types don't work (e.g. "game", https://machine-vision.no/creative-work-publication-type/game). Funky enough, "topics" work. Further down, "game" works, but leads here: https://machine-vision.no/taxonomy/term/3 - so I guess it's just about the links in the introductory text.

That is just path alias that is not yet configured. Jump into issue #97 and we address the change to config there.

**Comment by steinmb** [comment]
>Add inline editing of Situations in the Creative Works entry. Now you can only add existing Situations, it would be nice to be able to add new Situations directly from the Creative Works entry.

You can add situations that do not exist. It is a little counter intuitive as is, but if you ref. something that do not exist if will be created when you save the work and you can then edit it. Have a look at this:

[Screen Recording 2020-07-15 at 17.38.46.mp4.zip](https://github.com/jilltxt/machinevision/files/4926411/Screen.Recording.2020-07-15.at.17.38.46.mp4.zip)


For a improved inline editing I am holding back, waiting for this to get ready:
 https://www.drupal.org/project/inline_entity_form/issues/3121071

**Comment by jilltxt** [comment]
UPDATE: IGNORE THIS AS I HAVE NO IDEA WHAT I MEANT
I don’t think issue 2 here is actually a search issue, @steinmb - it’s that the fields are set up to autocomplete but they should be a pull down menu instead.

**Comment by steinmb** [comment]
I have created separate follow up issues, closing this.
